### ISSUE TITLE
LSM6DB0 support

### ISSUE THREAD

**Issue by Demon000** [STMicroelectronics/STMems_Android_Sensor_HAL_IIO#1]
How would I go about adding support for this chip?

I've only been able to find this chip in some Xiaomi devices, and there's no documentation on the STM site for it.

**Comment by mariotesi** [comment]
LSM6DB0 is not more supported, in any case the Accelerometer part is very similar to LSM9DS1 so is possible to reuse the HAL and driver of LSM9DS1
